### ISSUE TITLE
追加していない絵本を追加したと言われてしまう

### ISSUE THREAD

**Issue by risacan** [ikejirirb/konure#16]
<img width="370" alt="2017-11-21 15 23 45" src="https://user-images.githubusercontent.com/13192318/33057820-06b1ce8c-ced0-11e7-810a-db974538e51d.png">

**Comment by katorie** [comment]
https://github.com/ikejirirb/konure/blob/master/lib/ruboty/handlers/ehon.rb#L15

リストが空だと `nil` になって `else` に飛んでまう
